name: Fly.io Setup
description: Setup flyctl and load environment configuration

inputs:
    fly-api-token:
        description: Fly.io API token
        required: true

runs:
    using: composite
    steps:
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Load environment
          shell: bash
          run: |
              FLY_ORG="your-org"
              FLY_API_TOKEN="${{ inputs.fly-api-token }}"
              FLY_APP_NAME=$(jq -r .app fly.json)
              FLY_PRIMARY_REGION=$(jq -r .primary_region fly.json)

              test -n "$FLY_API_TOKEN" || { echo "Missing fly-api-token"; exit 1; }
              test -n "$FLY_APP_NAME" || { echo "Missing .app in fly.json"; exit 1; }
              test -n "$FLY_PRIMARY_REGION" || { echo "Missing .primary_region in fly.json"; exit 1; }

              cat >> "$GITHUB_ENV" <<EOF
              FLY_API_TOKEN=$FLY_API_TOKEN
              FLY_APP_NAME=$FLY_APP_NAME
              FLY_PRIMARY_REGION=$FLY_PRIMARY_REGION
              FLY_ORG=$FLY_ORG
              EOF
