name: Deploy App
on:
    push:
        branches: [main]

jobs:
    deploy:
        uses: ./.github/workflows/fly.common.yml
        with:
            bootstrap: false
        secrets: inherit

    set-secrets:
        needs: deploy
        uses: ./.github/workflows/fly-set-secrets.yml
        secrets: inherit
