name: Deploy App
on:
    push:
        branches: [main]

jobs:
    set-secrets:
        uses: ./.github/workflows/fly-set-secrets.yml
        with:
            stageBeforeDeploy: true
        secrets: inherit

    deploy:
        needs: set-secrets
        uses: ./.github/workflows/fly.common.yml
        with:
            bootstrap: false
        secrets: inherit
